spring:
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        - id: quote
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/quote
          filters:
            -
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@apiKeyResolver}'
                redis-rate-limiter.replenishRate: 1000   # 高优先级API QPS
                redis-rate-limiter.burstCapacity: 200
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/order
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@apiKeyResolver}'
                redis-rate-limiter.replenishRate: 300    # 中优先级API QPS
                redis-rate-limiter.burstCapacity: 50
        - id: low
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/low
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@apiKeyResolver}'
                redis-rate-limiter.replenishRate: 50     # 低优先级API QPS
                redis-rate-limiter.burstCapacity: 10